/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estructura_archivos;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author carlosjaime
 */
public class Archivos extends javax.swing.JFrame {

    private Editor editorClass;
    
    public Archivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        saveAsButton = new javax.swing.JButton();
        saveAllButton = new javax.swing.JButton();
        closeAllButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        contenedorTP = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });
        jPanel2.add(newButton);

        openButton.setText("Open");
        jPanel2.add(openButton);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel2.add(saveButton);

        closeButton.setText(" Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(closeButton);

        saveAsButton.setText("Save As");
        saveAsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsButtonActionPerformed(evt);
            }
        });
        jPanel2.add(saveAsButton);

        saveAllButton.setText("Save All");
        saveAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAllButtonActionPerformed(evt);
            }
        });
        jPanel2.add(saveAllButton);

        closeAllButton.setText("Close All");
        jPanel2.add(closeAllButton);

        jTabbedPane1.addTab("tab1", jPanel2);

        jButton3.setText("Nuevo");
        jPanel3.add(jButton3);

        jButton4.setText("Abrir");
        jPanel3.add(jButton4);

        jButton5.setText("Guardar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jTabbedPane1.addTab("tab2", jPanel3);

        jToolBar1.add(jTabbedPane1);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(jTree2);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.LINE_START);
        jPanel1.add(contenedorTP, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        String nombreArchivo = JOptionPane.showInputDialog("Cual es el nombre del archivo");
        String extensionArchivo = ".txt";
        String nombreCompleto = nombreArchivo.concat(extensionArchivo);
        
        editorClass = new Editor(nombreCompleto);
        contenedorTP.add(nombreArchivo, editorClass);
    }//GEN-LAST:event_newButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.out.println(contenedorTP.getSelectedComponent());
        System.out.println(contenedorTP.getSelectedIndex());
        int selectedIndex = contenedorTP.getSelectedIndex();
        editorClass = (Editor) contenedorTP.getSelectedComponent();
        System.out.println(editorClass.getFile().getName());
        

    int cerrar = JOptionPane.showConfirmDialog(contenedorTP, "Desea cerrar sin guardar?", "Cerrar", JOptionPane.YES_NO_OPTION);
        if (cerrar == JOptionPane.NO_OPTION) {
            editorClass = (Editor) contenedorTP.getSelectedComponent();
            String content = editorClass.getjEditorPane1().getText();

            try (FileWriter writer = new FileWriter(editorClass.getFile().getName());
                BufferedWriter bw = new BufferedWriter(writer)) {
                bw.write(content);
            } catch (IOException e) {
                System.err.format("IOException: %s%n", e);
            }
        }
        contenedorTP.remove(selectedIndex);
        //
    }//GEN-LAST:event_closeButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        editorClass = (Editor) contenedorTP.getSelectedComponent();
        String content = editorClass.getjEditorPane1().getText();

        try (FileWriter writer = new FileWriter(editorClass.getFile().getName());
            BufferedWriter bw = new BufferedWriter(writer)) {
            bw.write(content);
        } catch (IOException e) {
            System.err.format("IOException: %s%n", e);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void saveAsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsButtonActionPerformed
        String nombreArchivo = JOptionPane.showInputDialog("Guardar como?");
        String extensionArchivo = ".txt";
        String nombreCompleto = nombreArchivo.concat(extensionArchivo);
        
        editorClass = (Editor) contenedorTP.getSelectedComponent();
        String content = editorClass.getjEditorPane1().getText();

        try (FileWriter writer = new FileWriter(nombreCompleto);
            BufferedWriter bw = new BufferedWriter(writer)) {
            bw.write(content);
            contenedorTP.setTitleAt(contenedorTP.getSelectedIndex(), nombreArchivo);
        } catch (IOException e) {
            System.err.format("IOException: %s%n", e);
        }
    }//GEN-LAST:event_saveAsButtonActionPerformed

    private void saveAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAllButtonActionPerformed
        //System.out.println(contenedorTP.getTabCount());
        for (int i = 0; i < contenedorTP.getTabCount(); i++) {
            editorClass = (Editor) contenedorTP.getComponentAt(i);
            String content = editorClass.getjEditorPane1().getText();

            try (FileWriter writer = new FileWriter(editorClass.getFile().getName());
                BufferedWriter bw = new BufferedWriter(writer)) {
                bw.write(content);
            } catch (IOException e) {
                System.err.format("IOException: %s%n", e);
            }
        }
    }//GEN-LAST:event_saveAllButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Archivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeAllButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTabbedPane contenedorTP;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTree jTree2;
    private javax.swing.JButton newButton;
    private javax.swing.JButton openButton;
    private javax.swing.JButton saveAllButton;
    private javax.swing.JButton saveAsButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
